"""The financial domain's column contracts, one per statement plus metrics.

No source supplies every declared column: each provider requests the upstream
fields it knows how to name, and the projection fills the rest with ``NaN``.
The gap is the point — it is part of the published contract rather than a
surprise found by whoever selects a documented column.

A future pass could narrow the gap by extending a provider's upstream field
map; nothing here guesses upstream field codes.
"""

from __future__ import annotations

#: report_date, currency, total_assets, current_assets, cash_and_equivalents,
#: inventory, current_investments, trade_and_non_trade_receivables,
#: non_current_assets, property_plant_and_equipment,
#: goodwill_and_intangible_assets, investments, non_current_investments,
#: outstanding_shares, tax_assets, total_liabilities, current_liabilities,
#: current_debt, trade_and_non_trade_payables, deferred_revenue,
#: deposit_liabilities, non_current_liabilities, non_current_debt,
#: tax_liabilities, shareholders_equity, retained_earnings,
#: accumulated_other_comprehensive_income, accounts_receivable, prepayments,
#: other_receivables, fixed_assets_net, construction_in_progress,
#: capital_reserve, current_ratio, debt_to_assets, minority_interest
BALANCE_COLUMNS = (
    "report_date",
    "currency",
    "total_assets",
    "current_assets",
    "cash_and_equivalents",
    "inventory",
    "current_investments",
    "trade_and_non_trade_receivables",
    "non_current_assets",
    "property_plant_and_equipment",
    "goodwill_and_intangible_assets",
    "investments",
    "non_current_investments",
    "outstanding_shares",
    "tax_assets",
    "total_liabilities",
    "current_liabilities",
    "current_debt",
    "trade_and_non_trade_payables",
    "deferred_revenue",
    "deposit_liabilities",
    "non_current_liabilities",
    "non_current_debt",
    "tax_liabilities",
    "shareholders_equity",
    "retained_earnings",
    "accumulated_other_comprehensive_income",
    "accounts_receivable",
    "prepayments",
    "other_receivables",
    "fixed_assets_net",
    "construction_in_progress",
    "capital_reserve",
    "current_ratio",
    "debt_to_assets",
    "minority_interest",
)

#: report_date, currency, revenue, operating_revenue, total_operating_costs,
#: cost_of_revenue, operating_profit,
#: selling_general_and_administrative_expenses, operating_expense,
#: research_and_development, interest_expense, ebit, income_tax_expense,
#: net_income, net_income_common_stock, net_income_non_controlling_interests,
#: earnings_per_share, earnings_per_share_diluted, investment_income,
#: fair_value_adjustments, asset_impairment_loss, financial_expenses,
#: taxes_and_surcharges, other_comprehensive_income, total_comprehensive_income
INCOME_COLUMNS = (
    "report_date",
    "currency",
    "revenue",
    "operating_revenue",
    "total_operating_costs",
    "cost_of_revenue",
    "operating_profit",
    "selling_general_and_administrative_expenses",
    "operating_expense",
    "research_and_development",
    "interest_expense",
    "ebit",
    "income_tax_expense",
    "net_income",
    "net_income_common_stock",
    "net_income_non_controlling_interests",
    "earnings_per_share",
    "earnings_per_share_diluted",
    "investment_income",
    "fair_value_adjustments",
    "asset_impairment_loss",
    "financial_expenses",
    "taxes_and_surcharges",
    "other_comprehensive_income",
    "total_comprehensive_income",
)

#: report_date, currency, net_cash_flow_from_operations, capital_expenditure,
#: business_acquisitions_and_disposals, net_cash_flow_from_investing,
#: issuance_or_repayment_of_debt_securities,
#: issuance_or_purchase_of_equity_shares, net_cash_flow_from_financing,
#: change_in_cash_and_equivalents, effect_of_exchange_rate_changes,
#: ending_cash_balance, cash_from_sales, tax_refunds_received,
#: cash_paid_to_employees, taxes_paid, total_cash_inflow_from_operations,
#: total_cash_outflow_from_operations, cash_from_investment_recovery,
#: cash_from_investment_income, cash_from_asset_sales,
#: total_cash_inflow_from_investing, total_cash_outflow_from_investing,
#: cash_paid_for_dividends_and_interest, cash_paid_for_debt_repayment,
#: total_cash_inflow_from_financing, total_cash_outflow_from_financing,
#: beginning_cash_balance, ending_cash, ending_cash_equivalents
CASH_FLOW_COLUMNS = (
    "report_date",
    "currency",
    "net_cash_flow_from_operations",
    "capital_expenditure",
    "business_acquisitions_and_disposals",
    "net_cash_flow_from_investing",
    "issuance_or_repayment_of_debt_securities",
    "issuance_or_purchase_of_equity_shares",
    "net_cash_flow_from_financing",
    "change_in_cash_and_equivalents",
    "effect_of_exchange_rate_changes",
    "ending_cash_balance",
    "cash_from_sales",
    "tax_refunds_received",
    "cash_paid_to_employees",
    "taxes_paid",
    "total_cash_inflow_from_operations",
    "total_cash_outflow_from_operations",
    "cash_from_investment_recovery",
    "cash_from_investment_income",
    "cash_from_asset_sales",
    "total_cash_inflow_from_investing",
    "total_cash_outflow_from_investing",
    "cash_paid_for_dividends_and_interest",
    "cash_paid_for_debt_repayment",
    "total_cash_inflow_from_financing",
    "total_cash_outflow_from_financing",
    "beginning_cash_balance",
    "ending_cash",
    "ending_cash_equivalents",
)

#: report_date, total_assets, fixed_assets_net, cash_and_equivalents,
#: accounts_receivable, inventory, trade_and_non_trade_payables,
#: deferred_revenue, total_liabilities, shareholders_equity, revenue,
#: total_operating_costs, operating_profit, net_income_common_stock,
#: net_cash_flow_from_operations, net_cash_flow_from_investing,
#: net_cash_flow_from_financing, change_in_cash_and_equivalents
METRICS_COLUMNS = (
    "report_date",
    "total_assets",
    "fixed_assets_net",
    "cash_and_equivalents",
    "accounts_receivable",
    "inventory",
    "trade_and_non_trade_payables",
    "deferred_revenue",
    "total_liabilities",
    "shareholders_equity",
    "revenue",
    "total_operating_costs",
    "operating_profit",
    "net_income_common_stock",
    "net_cash_flow_from_operations",
    "net_cash_flow_from_investing",
    "net_cash_flow_from_financing",
    "change_in_cash_and_equivalents",
)
